### ISSUE TITLE
Exercises: Q1.c

### ISSUE THREAD

**Issue by ddbortoli** [LDSSA/batch2-BLU07#3]
It's unclear from the instructions what counts as a variant of the word `pass`.
Anything that starts with `pass`, followed by 0 or more characters of any kind?
Even if it's part of a word that has nothing to do with `password`, e.g. `passport`?

**Comment by Tassakhi** [comment]
pass, password, passpass

Here you can use (pass with 0 or 1 character | pass with some character at the end (but No digits) ). The trick is just write regex for the above three words.

**Comment by PedroMLF** [comment]
The purpose of the question is to find the variations of the word `pass` (so `passport` would be correct).

It should have been said prefix instead of word in that sentence, I agree. Also, digits are not being included in the solution.

**Comment by orlandocosta76** [comment]
If I may add, we should keep in mind that we're looking for whole words match and not simply a partial match (I had that problem)
