### ISSUE TITLE
Exercises: Q4 - Recursion Limit

### ISSUE THREAD

**Issue by Bennylave** [LDSSA/batch2-BLU07#6]
Whenever I run the asserts in Q4 .a), I get the following : "RecursionError : maximum recursion depth exceeded".
I already tried setting different recursion limits with sys.setrecursionlimit() but either I get the same Recursion error or my kernel dies.
Is there any other way of solving this?

**Comment by PedroMLF** [comment]
It seems that you're implementing the n-gram function incorrectly. Send me a DM via slack with your current solution so I can help you :)
