### ISSUE TITLE
Exercises Q2a: different number of tokens

### ISSUE THREAD

**Issue by pma2** [LDSSA/batch2-BLU07#7]
I get 2545 tokens instead of the expected 2582. I am using a common tokenizer from nltk. Any problem with assert? Any advice? Thanks

**Comment by PedroMLF** [comment]
Are you using the WordPunctTokenizer?

**Comment by pma2** [comment]
Yes.

**Comment by PedroMLF** [comment]
Ok. Send me your solution via slack so I can discuss it with you.

**Comment by pma2** [comment]
Resolved! Was a problem with the process of reading the file.
