### ISSUE TITLE
Q4b) "the highest value of n, before the most common n-gram starts to be unique?"

### ISSUE THREAD

**Issue by FilipaRodrigues** [LDSSA/batch2-BLU07#8]
I'm having difficulties to understand how we can get this number. 

The logic that I apply to it is to experiment some n values and having the most common n-grams. But I can't see a pattern or something going different from some n values to anothers. 

Can someone give me some light about this question?

**Comment by orlandocosta76** [comment]
@FilipaRodrigues  If you have some text, the most common n-gram for some value, let's say n=2, could be _"that is"_ which occurs, for instance 10 times. 
Then,  you increase the value of n to 3, and the resulting most common n-gram is _"let it be"_  which occurs 5 times. 
Now, you keep increasing the n until there is a time where the most common n-gram occurs only 1 time, and what you want as a result is the value of  n-1 (which is the value of the most common n-gram before its occurrences start to be unique, i.e. take the value of 1).

**Comment by FilipaRodrigues** [comment]
Thank you @orlandocosta76. That's what I've been thinking... 
I think I was a little bit confused because the assert dont pass using what I think is the correct value of n, even if I named it answer. There is something wrong with it, I will be posting this issue in the one already open about it.
